console.log("Website Design & Developed By Aryan Sejani");const lightMode=document.querySelector(".light-mode");lightMode.addEventListener("click",function(){document.body.classList.toggle("light-theme");if(lightMode.innerHTML==="Light Mode"){lightMode.innerHTML="Dark Mode"}else{lightMode.innerHTML="Light Mode"}})-5
gsap.registerPlugin(ScrollTrigger,ScrollToPlugin);gsap.to("#section-projects",{top:"5vh",scrollTrigger:{trigger:"#section-home",start:"450% 88%",end:"450% 5%",scrub:2,}})
gsap.to("#section-about",{top:"9vh",scrollTrigger:{trigger:"#section-projects",start:"850% 92%",end:"850% 9%",scrub:2,}})
gsap.to("#section-contact",{top:"13.05vh",scrollTrigger:{trigger:"#section-about",start:"1150% 14%",end:"1250% 14%",scrub:2,}})
gsap.to("#home-header i",{rotate:"180deg",opacity:"1",scrollTrigger:{trigger:"#section-home",start:"450% 88%",end:"450% 5%",scrub:1,}})
gsap.to("#section-projects header i",{rotate:"205deg",scrollTrigger:{trigger:"#section-home",start:"450% 88%",end:"450% 5%",scrub:1,}})
gsap.to("#section-about  header i",{rotate:"160deg",scrollTrigger:{trigger:"#section-projects",start:"850% 92%",end:"850% 9%",scrub:1,}})
gsap.to("#section-contact  header i",{rotate:"190deg",opacity:0,scrollTrigger:{trigger:"#section-about",start:"1150% 14%",end:"1250% 14%",scrub:1,}})
var tl1=new TimelineMax({reversed:!0,});var tl2=new TimelineMax({reversed:!0,});var tl3=new TimelineMax({reversed:!0,});tl1.to(window,{duration:0.2,scrollTo:"#header-click-scroll",ease:"none"});tl2.to(window,{duration:0.2,scrollTo:"#header-click-scroll",ease:"none"});tl3.to(window,{duration:0.5,scrollTo:"max",ease:"none"});document.getElementById("projects-header").addEventListener('click',function(){if(tl1.reversed()){tl1.play()}else{tl1.reverse()}});document.getElementById("about-header").addEventListener('click',function(){if(tl2.reversed()){tl2.play()}else{tl2.reverse()}});document.getElementById("home-header").addEventListener('click',function(){if(tl3.reversed()){tl3.play(!1)}else{tl3.reverse()}});document.getElementById("contact-header").addEventListener('click',()=>{gsap.to(window,{duration:0.5,scrollTo:"max",ease:"none"})});ScrollTrigger.matchMedia({"(max-width:1350px )":function(){let sections=gsap.utils.toArray(".horizontal-scroll-panel");gsap.to(sections,{xPercent:-310*(sections.length-1),ease:"none",scrollTrigger:{trigger:".horizontal-scroll-container",pin:!0,scrub:2,end:()=>"+="+document.querySelector(".horizontal-scroll-container").offsetWidth}})},"(min-width:1351px)":function(){let sections=gsap.utils.toArray(".horizontal-scroll-panel");gsap.to(sections,{xPercent:-450*(sections.length-1),ease:"none",scrollTrigger:{trigger:".horizontal-scroll-container",pin:!0,scrub:2,end:()=>"+="+document.querySelector(".horizontal-scroll-container").offsetWidth}})},});gsap.to("#home-main-img img",{scale:"0.8",opacity:0.8,scrollTrigger:{trigger:"#section-home",start:"top",end:"50%",scrub:2,}})
gsap.to("#home-to-about-cta",{scale:"0.8",x:-60,y:-60,scrollTrigger:{trigger:"#section-home",start:"top",end:"50%",scrub:2,}})
gsap.to("#brand-name-home-1",{left:"47%",scrollTrigger:{trigger:"#section-home",start:"top",end:"50%",scrub:2,}})
gsap.to("#home-main-1-text-box",{left:"25%",scrollTrigger:{trigger:"#section-home",start:"top",end:"50%",scrub:2,}})
gsap.to("#construction-lottie",{left:"28%",scrollTrigger:{trigger:"#section-home",start:"top",end:"50%",scrub:2,}})
gsap.to("#home-main-slogan h1:nth-child(1)",{x:"-35%",scrollTrigger:{trigger:"#section-home",start:"10%",end:"80%",scrub:2,}})
gsap.to("#home-main-slogan h1:nth-child(2)",{x:"5%",scrollTrigger:{trigger:"#section-home",start:"10%",end:"80%",scrub:2,}})
gsap.to("#home-main-slogan h1:nth-child(3)",{x:"-30%",scrollTrigger:{trigger:"#section-home",start:"10%",end:"80%",scrub:2,}})
ScrollTrigger.matchMedia({"(max-width:1300px )":function(){gsap.to("#home-main-2-main-img-wrapper",{clipPath:"polygon(0 0, 100% 0, 100% 100% , 0% 100%)",scrollTrigger:{trigger:"#section-home",start:"40%",end:"40%",scrub:2,}})},"(min-width:1301px)":function(){gsap.to("#home-main-2-main-img-wrapper",{clipPath:"polygon(0 0, 100% 0, 100% 100% , 0% 100%)",scrollTrigger:{trigger:"#section-home",start:"60%",end:"60%",scrub:2,}})},});ScrollTrigger.matchMedia({"(max-width:1300px )":function(){gsap.to("#home-main-2-main-img-parallax-1",{width:"0%",scrollTrigger:{trigger:"#section-home",start:"40%",end:"140%",scrub:2,}})},"(min-width:1301px)":function(){gsap.to("#home-main-2-main-img-parallax-1",{width:"0%",scrollTrigger:{trigger:"#section-home",start:"50%",end:"150%",scrub:2,}})},});ScrollTrigger.matchMedia({"(max-width:1300px )":function(){gsap.to("#home-main-2-main-img-parallax-2",{width:"30%",scrollTrigger:{trigger:"#section-home",start:"40%",end:"140%",scrub:2,}})},"(min-width:1301px)":function(){gsap.to("#home-main-2-main-img-parallax-2",{width:"30%",scrollTrigger:{trigger:"#section-home",start:"50%",end:"150%",scrub:2,}})},});ScrollTrigger.matchMedia({"(max-width:1300px )":function(){let tl=gsap.timeline({scrollTrigger:{trigger:"#section-home",start:"70%",end:"100%",scrub:2,}})
tl.fromTo("#home-main-2-contact-cta",{rotation:-90,left:"38%"},{rotation:90,left:"65%"})},"(min-width:1301px)":function(){let tl=gsap.timeline({scrollTrigger:{trigger:"#section-home",start:"120%",end:"160%",scrub:2,}})
tl.fromTo("#home-main-2-contact-cta",{rotation:-90,left:"38%"},{rotation:90,left:"65%"})},});ScrollTrigger.matchMedia({"(max-width:1300px )":function(){gsap.to("#animated-brand-name-main-2",{top:"-350%",scrollTrigger:{trigger:"#section-home",start:"80%",end:"180%",scrub:2,}})},"(min-width:1301px)":function(){gsap.to("#animated-brand-name-main-2",{top:"-350%",scrollTrigger:{trigger:"#section-home",start:"130%",end:"230%",scrub:2,}})},});ScrollTrigger.matchMedia({"(max-width:1300px )":function(){gsap.to("#home-main-3-p-text",{clipPath:"polygon(100% 100%, 100% 0, 0 0, 0 100%)",scrollTrigger:{trigger:"#section-home",start:"100%",end:"100%",scrub:2,}})},"(min-width:1301px)":function(){gsap.to("#home-main-3-p-text",{clipPath:"polygon(100% 100%, 100% 0, 0 0, 0 100%)",scrollTrigger:{trigger:"#home-main-3",start:"140%",end:"140%",scrub:2,}})},});ScrollTrigger.matchMedia({"(max-width:1300px )":function(){gsap.to("#home-main-3-p-img",{clipPath:"polygon(0% 0%, 100% 0%, 100% 100%, 0% 100%)",scrollTrigger:{trigger:"#section-home",start:"105%",end:"105%",scrub:2,}})},"(min-width:1301px)":function(){gsap.to("#home-main-3-p-img",{clipPath:"polygon(0% 0%, 100% 0%, 100% 100%, 0% 100%)",scrollTrigger:{trigger:"#section-home",start:"150%",end:"150%",scrub:2,}})},});let proxy={skew:0},skewSetter=gsap.quickSetter(".skewElem","skewY","deg"),clamp=gsap.utils.clamp(-20,20);ScrollTrigger.create({onUpdate:(self)=>{let skew=clamp(self.getVelocity()/-300);if(Math.abs(skew)>Math.abs(proxy.skew)){proxy.skew=skew;gsap.to(proxy,{skew:0,duration:0.8,ease:"power3",overwrite:!0,onUpdate:()=>skewSetter(proxy.skew)})}}});gsap.set(".skewElem",{transformOrigin:"center center",force3D:!1});const menuItemLink=document.getElementsByClassName("menu__item-link")
for(i=0;i<menuItemLink.length;i++){menuItemLink[i].addEventListener("mouseenter",function(){document.getElementById("home-main-3-hover-link").style.visibility="hidden"})}
for(i=0;i<menuItemLink.length;i++){menuItemLink[i].addEventListener("mouseleave",function(){document.getElementById("home-main-3-hover-link").style.visibility="visible"})}
gsap.to("#home-vertical-scroll-container-wrapper",{top:"-300%",scrollTrigger:{trigger:"#section-home",start:"top",end:"400%",scrub:2,}})
gsap.to("#home-mob-main-1-img img",{scale:"0.7",opacity:0.8,scrollTrigger:{trigger:"#section-home",start:"top",end:"50%",scrub:2,}})
gsap.to("#mob-home-to-about-cta",{scale:"0.7",x:-60,y:-60,scrollTrigger:{trigger:"#section-home",start:"top",end:"50%",scrub:2,}})
gsap.to("#mob-home-main-1-text-box",{top:"55%",scrollTrigger:{trigger:"#section-home",start:"20%",end:"60%",scrub:2,}})
gsap.to("#mob-home-main-slogan",{clipPath:"polygon(0 0, 100% 0, 100% 100% , 0% 100%)",scrollTrigger:{trigger:"#home-mob-main-1",start:"20%",end:"20%",scrub:2,}})
let MobLottie1=gsap.timeline({scrollTrigger:{trigger:"#home-mob-main-1",start:"40%",end:"60%",scrub:2,}})
MobLottie1.fromTo("#mob-construction-lottie",{opacity:0,y:"60"},{opacity:1,y:"0"})
gsap.to("#mob-home-main-3-contact-cta",{rotation:90,right:"10%",scrollTrigger:{trigger:"#home-mob-main-3",start:"-30%",end:"10%",scrub:2,}})
gsap.to("#mob-main-3-img img",{scale:1,scrollTrigger:{trigger:"#home-mob-main-3",start:"10%",end:"10%",scrub:2,}})
ScrollTrigger.matchMedia({"(min-width: 750px)":function(){gsap.to("#project-1",{left:"97%",scrollTrigger:{trigger:"#section-projects",start:"350% 9%",end:"450% 9%",scrub:0,}})},"(max-width:749px)":function(){gsap.to("#project-1",{left:"95%",scrollTrigger:{trigger:"#section-projects",start:"350% 9%",end:"450% 9%",scrub:0,}})},});ScrollTrigger.matchMedia({"(min-width: 750px)":function(){gsap.to("#project-2",{left:"94%",scrollTrigger:{trigger:"#section-projects",start:"450% 9%",end:"550% 9%",scrub:0,}})},"(max-width:749px)":function(){gsap.to("#project-2",{left:"90%",scrollTrigger:{trigger:"#section-projects",start:"450% 9%",end:"550% 9%",scrub:0,}})},});ScrollTrigger.matchMedia({"(min-width: 750px)":function(){gsap.to("#project-3",{left:"91%",scrollTrigger:{trigger:"#section-projects",start:"550% 9%",end:"650% 9%",scrub:0,}})},"(max-width:749px)":function(){gsap.to("#project-3",{left:"85%",scrollTrigger:{trigger:"#section-projects",start:"550% 9%",end:"650% 9%",scrub:0,}})},});ScrollTrigger.matchMedia({"(min-width: 750px)":function(){gsap.to("#project-4",{left:"88%",scrollTrigger:{trigger:"#section-projects",start:"650% 9%",end:"750% 9%",scrub:0,}})},"(max-width:749px)":function(){gsap.to("#project-4",{left:"80%",scrollTrigger:{trigger:"#section-projects",start:"650% 9%",end:"750% 9%",scrub:0,}})},});const projectsMoreNo=document.querySelectorAll(".projects-more-no")
document.getElementById("projects-more-no-1").addEventListener("mouseover",function(){for(i=0;i<projectsMoreNo.length;i++){projectsMoreNo[i].classList.remove("projects-more-no-hover")}
document.getElementById("projects-more-no-1").classList.add("projects-more-no-hover")});document.getElementById("projects-more-no-2").addEventListener("mouseover",function(){for(i=0;i<projectsMoreNo.length;i++){projectsMoreNo[i].classList.remove("projects-more-no-hover")}
document.getElementById("projects-more-no-2").classList.add("projects-more-no-hover")});document.getElementById("projects-more-no-3").addEventListener("mouseover",function(){for(i=0;i<projectsMoreNo.length;i++){projectsMoreNo[i].classList.remove("projects-more-no-hover")}
document.getElementById("projects-more-no-3").classList.add("projects-more-no-hover")});document.getElementById("projects-more-no-4").addEventListener("mouseover",function(){for(i=0;i<projectsMoreNo.length;i++){projectsMoreNo[i].classList.remove("projects-more-no-hover")}
document.getElementById("projects-more-no-4").classList.add("projects-more-no-hover")});document.getElementById("projects-more-no-5").addEventListener("mouseover",function(){for(i=0;i<projectsMoreNo.length;i++){projectsMoreNo[i].classList.remove("projects-more-no-hover")}
document.getElementById("projects-more-no-5").classList.add("projects-more-no-hover")});document.getElementById("projects-more-no-6").addEventListener("mouseover",function(){for(i=0;i<projectsMoreNo.length;i++){projectsMoreNo[i].classList.remove("projects-more-no-hover")}
document.getElementById("projects-more-no-6").classList.add("projects-more-no-hover")});document.getElementById("projects-more-no-7").addEventListener("mouseover",function(){for(i=0;i<projectsMoreNo.length;i++){projectsMoreNo[i].classList.remove("projects-more-no-hover")}
document.getElementById("projects-more-no-7").classList.add("projects-more-no-hover")});document.getElementById("projects-more-no-8").addEventListener("mouseover",function(){for(i=0;i<projectsMoreNo.length;i++){projectsMoreNo[i].classList.remove("projects-more-no-hover")}
document.getElementById("projects-more-no-8").classList.add("projects-more-no-hover")});const projectMoreImg=document.querySelectorAll(".projects-more-project-img-c")
document.getElementById("projects-more-no-1").addEventListener("mouseover",function(){for(i=0;i<projectMoreImg.length;i++){projectMoreImg[i].style.opacity="0"}
document.getElementById("projects-more-project-img-1").style.opacity="1"});document.getElementById("projects-more-no-2").addEventListener("mouseover",function(){for(i=0;i<projectMoreImg.length;i++){projectMoreImg[i].style.opacity="0"}
document.getElementById("projects-more-project-img-2").style.opacity="1"});document.getElementById("projects-more-no-3").addEventListener("mouseover",function(){for(i=0;i<projectMoreImg.length;i++){projectMoreImg[i].style.opacity="0"}
document.getElementById("projects-more-project-img-3").style.opacity="1"});document.getElementById("projects-more-no-4").addEventListener("mouseover",function(){for(i=0;i<projectMoreImg.length;i++){projectMoreImg[i].style.opacity="0"}
document.getElementById("projects-more-project-img-4").style.opacity="1"});document.getElementById("projects-more-no-5").addEventListener("mouseover",function(){for(i=0;i<projectMoreImg.length;i++){projectMoreImg[i].style.opacity="0"}
document.getElementById("projects-more-project-img-5").style.opacity="1"});document.getElementById("projects-more-no-6").addEventListener("mouseover",function(){for(i=0;i<projectMoreImg.length;i++){projectMoreImg[i].style.opacity="0"}
document.getElementById("projects-more-project-img-6").style.opacity="1"});document.getElementById("projects-more-no-7").addEventListener("mouseover",function(){for(i=0;i<projectMoreImg.length;i++){projectMoreImg[i].style.opacity="0"}
document.getElementById("projects-more-project-img-7").style.opacity="1"});document.getElementById("projects-more-no-8").addEventListener("mouseover",function(){for(i=0;i<projectMoreImg.length;i++){projectMoreImg[i].style.opacity="0"}
document.getElementById("projects-more-project-img-8").style.opacity="1"});const projectsMoreName=document.querySelectorAll(".projects-more-project-name")
const projectsMoreNameH2=document.querySelectorAll(".projects-more-project-name-h2")
document.getElementById("projects-more-no-1").addEventListener("mouseover",function(){for(i=0;i<projectsMoreName.length;i++){projectsMoreName[i].style.opacity="0"}
for(i=0;i<projectsMoreNameH2.length;i++){projectsMoreNameH2[i].style.transform="translateY(100%)"}
document.getElementById("projects-more-project-name-1").style.opacity="1";document.getElementById("projects-more-project-name-1-h2").style.transform="translateY(-5%)"});document.getElementById("projects-more-no-2").addEventListener("mouseover",function(){for(i=0;i<projectsMoreName.length;i++){projectsMoreName[i].style.opacity="0"}
for(i=0;i<projectsMoreNameH2.length;i++){projectsMoreNameH2[i].style.transform="translateY(100%)"}
document.getElementById("projects-more-project-name-2").style.opacity="1";document.getElementById("projects-more-project-name-2-h2").style.transform="translateY(-5%)"});document.getElementById("projects-more-no-3").addEventListener("mouseover",function(){for(i=0;i<projectsMoreName.length;i++){projectsMoreName[i].style.opacity="0"}
for(i=0;i<projectsMoreNameH2.length;i++){projectsMoreNameH2[i].style.transform="translateY(100%)"}
document.getElementById("projects-more-project-name-3").style.opacity="1";document.getElementById("projects-more-project-name-3-h2").style.transform="translateY(-5%)"});document.getElementById("projects-more-no-4").addEventListener("mouseover",function(){for(i=0;i<projectsMoreName.length;i++){projectsMoreName[i].style.opacity="0"}
for(i=0;i<projectsMoreNameH2.length;i++){projectsMoreNameH2[i].style.transform="translateY(100%)"}
document.getElementById("projects-more-project-name-4").style.opacity="1";document.getElementById("projects-more-project-name-4-h2").style.transform="translateY(-5%)"});document.getElementById("projects-more-no-5").addEventListener("mouseover",function(){for(i=0;i<projectsMoreName.length;i++){projectsMoreName[i].style.opacity="0"}
for(i=0;i<projectsMoreNameH2.length;i++){projectsMoreNameH2[i].style.transform="translateY(100%)"}
document.getElementById("projects-more-project-name-5").style.opacity="1";document.getElementById("projects-more-project-name-5-h2").style.transform="translateY(-5%)"});document.getElementById("projects-more-no-6").addEventListener("mouseover",function(){for(i=0;i<projectsMoreName.length;i++){projectsMoreName[i].style.opacity="0"}
for(i=0;i<projectsMoreNameH2.length;i++){projectsMoreNameH2[i].style.transform="translateY(100%)"}
document.getElementById("projects-more-project-name-6").style.opacity="1";document.getElementById("projects-more-project-name-6-h2").style.transform="translateY(-5%)"});document.getElementById("projects-more-no-7").addEventListener("mouseover",function(){for(i=0;i<projectsMoreName.length;i++){projectsMoreName[i].style.opacity="0"}
for(i=0;i<projectsMoreNameH2.length;i++){projectsMoreNameH2[i].style.transform="translateY(100%)"}
document.getElementById("projects-more-project-name-7").style.opacity="1";document.getElementById("projects-more-project-name-7-h2").style.transform="translateY(-5%)"});document.getElementById("projects-more-no-8").addEventListener("mouseover",function(){for(i=0;i<projectsMoreName.length;i++){projectsMoreName[i].style.opacity="0"}
for(i=0;i<projectsMoreNameH2.length;i++){projectsMoreNameH2[i].style.transform="translateY(100%)"}
document.getElementById("projects-more-project-name-8").style.opacity="1";document.getElementById("projects-more-project-name-8-h2").style.transform="translateY(-5%)"});gsap.to("#about-scroll-container-wrapper",{top:"-300%",scrollTrigger:{trigger:"#section-projects",start:"850% 5%",end:"1150% 14%",scrub:2,}})
gsap.to("#about-main-2-box-1 h1",{x:-600,scrollTrigger:{trigger:"#section-projects",start:"800% 5%",end:"1100% 14%",scrub:2,}})
gsap.to("#about-main-2-box-3 h1",{x:-600,scrollTrigger:{trigger:"#section-projects",start:"800% 5%",end:"1100% 14%",scrub:2,}})
gsap.to("#about-main-2-box-2 h1",{x:400,scrollTrigger:{trigger:"#section-projects",start:"800% 5%",end:"1100% 14%",scrub:2,}})
ScrollTrigger.matchMedia({"(min-width: 901px)":function(){let teamImg=gsap.timeline({scrollTrigger:{trigger:"#section-projects",start:"950%",end:"950%",scrub:2,}})
teamImg.fromTo("#team-img",{rotation:15,y:"5%"},{rotation:0,y:"0%",duration:1})
teamImg.fromTo("#team-img img",{scale:1.5},{scale:1,duration:1},"-=1")
teamImg.fromTo("#team-title-box span",{rotate:45,},{rotate:25,duration:1},"-=1")},"(max-width:900px)":function(){let teamImg=gsap.timeline({scrollTrigger:{trigger:"#section-projects",start:"930%",end:"930%",scrub:2,}})
teamImg.fromTo("#team-img",{rotation:15,y:"5%"},{rotation:0,y:"0%",duration:1})
teamImg.fromTo("#team-img img",{scale:1.5},{scale:1,duration:1},"-=1")
teamImg.fromTo("#team-title-box span",{rotate:45,},{rotate:25,duration:1},"-=1")},});ScrollTrigger.matchMedia({"(min-width: 901px)":function(){let teamTitle=gsap.timeline({scrollTrigger:{trigger:"#section-projects",start:"940%",end:"940%",scrub:2,}})
teamTitle.fromTo("#team-title-box h1",{y:"-110%",},{y:"0%",duration:1})
teamTitle.fromTo("#team-img",{opacity:0,y:"15%"},{opacity:1,y:"5%",duration:1},"-=1")
teamTitle.fromTo("#team-title-box span",{rotate:0,},{rotate:45,duration:1},"-=1")},"(max-width:900px)":function(){let teamTitle=gsap.timeline({scrollTrigger:{trigger:"#section-projects",start:"910%",end:"910%",scrub:2,}})
teamTitle.fromTo("#team-title-box h1",{y:"-110%",},{y:"0%",duration:1})
teamTitle.fromTo("#team-img",{opacity:0,y:"15%"},{opacity:1,y:"5%",duration:1},"-=1")
teamTitle.fromTo("#team-title-box span",{rotate:0,},{rotate:45,duration:1},"-=1")},});ScrollTrigger.matchMedia({"(min-width: 901px)":function(){let teamSlogan=gsap.timeline({scrollTrigger:{trigger:"#section-projects",start:"955%",end:"955%",scrub:2,}})
teamSlogan.fromTo("#team-slogan",{opacity:0,y:"20%",},{opacity:1,y:"0%",duration:1})},"(max-width:900px)":function(){let teamSlogan=gsap.timeline({scrollTrigger:{trigger:"#section-projects",start:"955%",end:"955%",scrub:2,}})
teamSlogan.fromTo("#team-img-about",{opacity:0,y:"20%",},{opacity:1,y:"0%",duration:1})},});gsap.to("#contact-scroll-container-wrapper",{top:"-50%",scrollTrigger:{trigger:"#section-projects",start:"1250% 14%",end:"1300% 18%",scrub:2,}})